source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'FabricSimpleRisk_Example' do
  pod 'FabricSimpleRisk', :path => '../'
  pod 'ForterSDK', :git => 'https://bitbucket.org/forter-mobile/forter-ios-sdk.git', :tag => "3.0.4"
  target 'FabricSimpleRisk_Tests' do
    inherit! :search_paths

    
  end
end
