source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'FabricSimpleRisk_Example' do
  pod 'FabricSimpleRisk', :path => '../'
  target 'FabricSimpleRisk_Tests' do
    inherit! :search_paths

    
  end
end
